# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ADmIDiMygNasXizY4BJmt0NupK_z0rTe
"""

import pandas as pd
import numpy as np
import sqlite3

df = pd.read_csv('Music.csv')

df.dropna(subset=['name', 'artist'], inplace=True)
df.drop_duplicates(subset=['name', 'artist'], keep='first', inplace=True)

df['title'] = df['name']

cond_1 = (df['energy'] >= 0.7) & (df['valence'] >= 0.5)
cond_2 = (df['energy'] >= 0.7) & (df['valence'] < 0.5)
cond_3 = (df['energy'] < 0.7) & (df['valence'] >= 0.5)
cond_4 = (df['energy'] < 0.4)

conditions = [cond_1, cond_2, cond_3, cond_4]
choices = ['Dance', 'Rock', 'Pop', 'Classical']

df['genre'] = np.select(conditions, choices, default='Jazz')

print("Step 1 Successful! Total songs loaded:", df.shape[0])

df['image_url'] = df['img']

df = df.reset_index(drop=True)
df['file_path'] = 'song' + (df.index + 1).astype(str) + '.mp3'

conn = sqlite3.connect('music.db')
cursor = conn.cursor()
df_final = df[['title', 'artist', 'genre', 'energy', 'file_path', 'image_url']].copy()
df_final.to_sql('songs', conn, if_exists='replace', index=True, index_label='id')
cursor.execute("UPDATE songs SET id = id + 1;")
conn.commit()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print("Tables now inside music.db:", cursor.fetchall())

conn.close()

